module.exports = {
  crawlerOptions: {
    basicCrawlerOptions: {
      keepAlive: true,
      maxConcurrency: 100,
      maxRequestRetries: 2,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 200,
      minConcurrency: 1,
      requestHandlerTimeoutSecs: 60,
    },
    cheerioCrawlerOptions: {
      keepAlive: true,
      maxConcurrency: 100,
      maxRequestRetries: 2,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 200,
      minConcurrency: 1,
      navigationTimeoutSecs: 60,
      requestHandlerTimeoutSecs: 60,
    },
    jsdomCrawlerOptions: {
      hideInternalConsole: false,
      keepAlive: true,
      maxConcurrency: 100,
      maxRequestRetries: 2,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 200,
      minConcurrency: 1,
      navigationTimeoutSecs: 60,
      requestHandlerTimeoutSecs: 60,
      runScripts: false,
    },
    playwrightCrawlerOptions: {
      headless: true,
      keepAlive: true,
      maxConcurrency: 100,
      maxRequestRetries: 2,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 200,
      minConcurrency: 1,
      navigationTimeoutSecs: 60,
      requestHandlerTimeoutSecs: 60,
    },
    puppeteerCrawlerOptions: {
      headless: true,
      keepAlive: true,
      maxConcurrency: 100,
      maxRequestRetries: 2,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 200,
      minConcurrency: 1,
      navigationTimeoutSecs: 60,
      requestHandlerTimeoutSecs: 60,
    },
  },
  domains: require("./domains"),
  handledDomains: require("./handled-domains"),
  proxies: require("./proxies"),
};
